# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
